CREATE TABLE SEASON_CNST AS (
SELECT
playerID,
name,
AVG(SEASON_CNST) AS SEASON_CNST,
AVG(GP) AS GP,
AVG(FPTS) AS FPTS
FROM
(
SELECT
*,
CASE WHEN NAME = LAG(NAME) OVER (ORDER BY PLAYERID, SEASON) THEN 
	FPTS - LAG(FPTS) OVER (ORDER BY PLAYERID, SEASON) END
AS SEASON_CNST
FROM PLAYER_SEASON_FPTS

) a


GROUP BY 1,2
ORDER BY 3 DESC
)
