CREATE TABLE WKLY_CNST AS (
SELECT playerID,
name,
SUM(WKLY_CNST) AS WKLY_CNST,
AVG(FPTS) AS FPTS
FROM 
(
SELECT
*,
CASE WHEN NAME = LAG(NAME) OVER (ORDER BY PLAYERID, WEEK) THEN
	CASE WHEN FPTS > LAG(FPTS) OVER (ORDER BY PLAYERID, WEEK) THEN 1 ELSE -1 END
ELSE 0 
END AS WKLY_CNST
FROM PLAYER_WEEKLY_FPTS 
) a
GROUP BY 1,2 ORDER BY 3 DESC
)
